name: Build and deploy .NET Core application to Web App MoyoProjectAPI20240730140313 with API Management Service MoyoProjectAPIapi-MoyoProjectAPI
on:
  push:
    branches:
      - master
env:
  AZURE_WEBAPP_NAME: MoyoProjectAPI20240730140313
  AZURE_WEBAPP_PACKAGE_PATH: MoyoProjectAPI/publish
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: Moyo
  AZURE_APIM_SERVICENAME: MoyoProjectAPIapi
  AZURE_APIM_API_ID: MoyoProjectAPI
  AZURE_APIM_APPSERVICEURL: https://moyoprojectapi20240730140313.azurewebsites.net
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 5.6.3
  SWASHBUCKLE_DOTNET_CORE_VERSION: 6.2.3
  API_IMPORT_SPECIFICATION_PATH: MoyoProjectAPI/publish/swagger.json
  API_IMPORT_DLL: MoyoProjectAPI/bin/Release/net6.0/MoyoProjectAPI.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: MoyoProjectAPI

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
          
      - name: Setup Swashbuckle CLI .NET Global Tool
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version ${{ env.SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION }}
        
      - name: Restore
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}
        
      - name: Build
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore
        
      - name: Test
        run: dotnet test ${{ env.WORKING_DIRECTORY }} --no-build
        
      - name: Publish
        run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
      - name: Generate Open API Specification Document
        run: swagger tofile --output "${{ env.API_IMPORT_SPECIFICATION_PATH }}" "${{ env.API_IMPORT_DLL }}" "${{ env.API_IMPORT_VERSION }}"
        env:
          PATH: ${{ env.PATH }}:~/.dotnet/tools  # Ensure the global tools path is included in the PATH environment variable

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.MoyoProjectAPI20240730140313_685B }}
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MoyoProjectAPIapi_SPN }}
          
      - name: Import API into Azure API Management
        run: az apim api import --path "${{ env.AZURE_APIM_RESOURCE_PATH }}" --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" --service-name "${{ env.AZURE_APIM_SERVICENAME }}" --api-id "${{ env.AZURE_APIM_API_ID }}" --service-url "${{ env.AZURE_APIM_APPSERVICEURL }}" --specification-path "${{ env.API_IMPORT_SPECIFICATION_PATH }}" --specification-format OpenApi --subscription-required false
          
      - name: Logout
        run: az logout
